services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - my_network
    ports:
      - "8080:80"
    
  
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my_network
    ports:
      - "5672:5672"   # Porta padrão para AMQP
      - "15672:15672" # Porta padrão para a interface de gerenciamento
      - "5552:5552"   # Porta para RabbitMQ Streams


networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
